# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

# Dependencies
markdown:         kramdown
highlighter:      rouge  # pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Te-Chi's Tech Note
tagline:          A Web Dev's Playground
description:      Web dev learning notes and reviews.Sharing my discovery of web tech and open source.
url:              https://liuderchi.github.io
baseurl:          /blog  #/

author:
  name:           'Te-Chi Liu'
  githubURL:      https://github.com/liuderchi

paginate:         5
